my_string = input('Название курсов: ')
print('Количество символов: ', len(my_string))
print(my_string.lower() , my_string.upper())
print(my_string.replace(' ',''))
print(my_string[0] , my_string[-1])